### ISSUE TITLE
Prevent form freezing when executing methods

### ISSUE THREAD

**Issue by VRCWizard** [Sergey004/Quest2-VRC#6]
There are various ways to solve this issue I personally use ```Task.Run(() => MethodName())``` to allow methods to run without freezing the main form. Although I don't know if this is the most proper way of doing it. Here are some other examples: https://stackoverflow.com/questions/19134702/form-freezes-when-executing-method

**Comment by Sergey004** [comment]
Fixed in 4212a8f
