### ISSUE TITLE
AirLink connection

### ISSUE THREAD

**Issue by WereWolfix** [Sergey004/Quest2-VRC#7]
Not sure if this is a real issue or I am just stupid but every time I open Quest2_VRC.GUI.exe I have to connect my Quest to USB and than connecting to AirLink.
Is there a way to not do that every time?

When I try to use it with AirLink it doesn't find my headset even tho is connected with AirLink

**Comment by Sergey004** [comment]
Sorry, but this is how wireless ADB works on Quest, in the software version for Quest V51 ADB over wifi works all the time, but this is not what I have checked. Closing this Issue

**Comment by Sergey004** [comment]
Fixed in 62e59e040a381fe3ab4c4f0fc6dacf26f851a8ab
